<a id="linear-algebra-section"></a>
# Week 1: Linear Algebra for ML

### Why are we learning this?
In Machine Learning, we don't deal with single numbers; we deal with **Arrays**. 
* A **Scalar** is a single number: `5`
* A **Vector** is a list of numbers: `[5, 2, 9]`
* A **Matrix** is a grid of numbers.

### Key Operations to Master:
1. **Dot Product:** How models calculate weights.
2. **Matrix Multiplication:** How data flows through a neural network.
3. **Transpose:** Flipping a matrix (needed for certain math proofs).

In [1]:
import numpy as np

# 1. Create a Vector (1D Array)
vector = np.array([1, 2, 3])
print("Vector:", vector)

# 2. Create a Matrix (2D Array)
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix:\n", matrix)

# 3. Transpose the Matrix (Flip rows and columns)
print("Flipped Matrix:\n", matrix.T)

# 4. Dot Product (The core of ML math)
a = np.array([1, 2])
b = np.array([3, 4])
dot = np.dot(a, b)
print("Dot Product:", dot) # (1*3) + (2*4) = 11

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Flipped Matrix:
 [[1 3 5]
 [2 4 6]]
Dot Product: 11
